apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-web
  labels:
    app: backend-web
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-web
          image: vovimayhem/ember-fastboot-demo-backend:v2
          ports:
            - containerPort: 3000
              name: backend-web
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: secret_key_base
            - name: DEMO_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: demo_api_key
