apiVersion: v1
kind: Service
metadata:
  name: backend-web
  labels:
    app: backend

spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
