apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres

spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
