apiVersion: v1
kind: Service
metadata:
  name: frontend-web
  labels:
    app: frontend

spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
