# .semaphore/production-deploy.yml
version: v1.0
name: Deploy to production
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: Deploy
    task:
      env_vars:
        - name: ECR_IMAGE_NAME_BASE
          value: 564922552600.dkr.ecr.eu-central-1.amazonaws.com/vovimayhem/ember-fastboot-demo
      secrets:
        - name: AWS
      prologue:
        commands:
          - checkout
          # Log in to AWS ECR:
          - docker-compose --file .semaphore/ci-compose.yml run --rm aws_ecr_login | tr -d '\r' | bash
          # Get the Git branch name safe to use as a docker image tag:
          - export TAG_SAFE_BRANCH=$(echo ${SEMAPHORE_GIT_BRANCH} | tr '/' '-')
      jobs:
        - name: Build Backend Image
          commands:
            - export TESTING_IMAGE_TAG=${ECR_IMAGE_NAME_BASE}-backend:testing-${TAG_SAFE_BRANCH}
            - export IMAGE_TAG=${ECR_IMAGE_NAME_BASE}-backend:${TAG_SAFE_BRANCH}
            # Pull the image to use it as cache:
            - docker pull ${TESTING_IMAGE_TAG} ; docker pull ${IMAGE_TAG} ; docker pull ${ECR_IMAGE_NAME_BASE}-backend:latest ; echo "Layer cache ready"
            - docker-compose --file .semaphore/ci-compose.yml build backend_release
            # Push the BRANCH_NAME tag:
            - docker tag backend:latest ${IMAGE_TAG}
            - docker push ${IMAGE_TAG}
            # Push the "latest" tag:
            - docker tag backend:latest ${ECR_IMAGE_NAME_BASE}-backend:latest
            - docker push ${ECR_IMAGE_NAME_BASE}-backend:latest
        - name: Build Frontend Image
          commands:
            - export TESTING_IMAGE_TAG=${ECR_IMAGE_NAME_BASE}-frontend:testing-${TAG_SAFE_BRANCH}
            - export IMAGE_TAG=${ECR_IMAGE_NAME_BASE}-frontend:${TAG_SAFE_BRANCH}
            # Pull the image to use it as cache:
            - docker pull ${TESTING_IMAGE_TAG} ; docker pull ${IMAGE_TAG} ; docker pull ${ECR_IMAGE_NAME_BASE}-frontend:latest ; echo "Layer cache ready"
            - docker-compose --file .semaphore/ci-compose.yml build frontend_release
            # Push the BRANCH_NAME tag:
            - docker tag frontend:latest ${IMAGE_TAG}
            - docker push ${IMAGE_TAG}
            # Push the "latest" tag:
            - docker tag frontend:latest ${ECR_IMAGE_NAME_BASE}-frontend:latest
            - docker push ${ECR_IMAGE_NAME_BASE}-frontend:latest