# .semaphore/production-deploy.yml
version: v1.0
name: Deploy to production
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: Deploy Apps
    task:
      env_vars:
        - name: ECR_IMAGE_NAME_BASE
          value: 564922552600.dkr.ecr.eu-central-1.amazonaws.com/vovimayhem/ember-fastboot-demo
      secrets:
        - name: AWS
        - name: HEROKU
      prologue:
        commands:
          - checkout
          
          # Log in to AWS ECR:
          - docker-compose --file .semaphore/ci-compose.yml run --rm aws_ecr_login | tr -d '\r' | bash

          # Log in to the Heroku Container Registry:
          - heroku container:login
      jobs:
        - name: Deploy backend app
          commands:
            - export GIT_SHA_IMAGE_TAG=${ECR_IMAGE_NAME_BASE}-backend:${SEMAPHORE_GIT_SHA:0:7}
            
            # Pull the release image to use it as cache:
            - docker pull ${GIT_SHA_IMAGE_TAG} ; echo "Layer cache ready"
            
            # Generate the 'web' Dockerfile:
            - cd backend && echo "FROM ${GIT_SHA_IMAGE_TAG}" >> Dockerfile.web

            # Push the images:
            - heroku container:push --recursive --app vov-fastboot-demo-backend

            # Release the images:
            - heroku container:release web --app vov-fastboot-demo-backend

            # Run migrations:
            - heroku run rails db:migrate --app vov-fastboot-demo-backend
        
        - name: Deploy frontend app
          commands:
            - export GIT_SHA_IMAGE_TAG=${ECR_IMAGE_NAME_BASE}-frontend:${SEMAPHORE_GIT_SHA:0:7}
            
            # Pull the release image to use it as cache:
            - docker pull ${GIT_SHA_IMAGE_TAG} ; echo "Layer cache ready"
            
            # Generate the 'web' Dockerfile:
            - cd frontend && echo "FROM ${GIT_SHA_IMAGE_TAG}" >> Dockerfile.web

            # Push the images:
            - heroku container:push --recursive --app vovimayhem-ember-fastboot-demo

            # Release the images:
            - heroku container:release web --app vovimayhem-ember-fastboot-demo
